<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Konfirmasi Ulang Kata Sandi_repassword</name>
   <tag></tag>
   <elementGuidId>a72ab510-a25f-456a-bb89-ad1218156964</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='registration_cpassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#registration_cpassword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>32fbb022-7092-4f44-a15e-a35b55fb79b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>repassword</value>
      <webElementGuid>5494e81a-8969-47d6-8135-d69fbad1c26b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>db3eeb77-63d9-43cf-a185-ef84b170c933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>*******</value>
      <webElementGuid>20057a76-dd95-4086-8477-0b895736ad06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registration_cpassword</value>
      <webElementGuid>b82dc34f-f55d-4ef5-b204-760384fb0a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registration_cpassword&quot;)</value>
      <webElementGuid>bf98ac99-19fa-4c66-a5c7-ddc4156de7bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='registration_cpassword']</value>
      <webElementGuid>52e66cc4-a7ca-4cad-9083-5f7f759a2e49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_registration']/p[4]/div/div/input</value>
      <webElementGuid>27079373-5e8e-4cda-8f10-1ca1adfecbc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[4]/div/div/input</value>
      <webElementGuid>a65231f1-cebe-4e9b-ae3e-0a8c8390538f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'repassword' and @type = 'password' and @placeholder = '*******' and @id = 'registration_cpassword']</value>
      <webElementGuid>da4a7484-5724-499e-94d2-9be05b3921c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
